services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: cafefausse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Passw0rd4132
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
      - DB_CONN_STR=postgresql://postgres:Passw0rd4132@db:5432/cafefausse
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api
    restart: unless-stopped

volumes:
  db_data:
